// Un ejemplo válido por DTO (solo tests; excluido de cobertura).
import type { z } from 'zod';
import * as dto from '../index.js';

const ID = '3f2b8c1e-5d4a-4e7b-9c2d-1a0b9e8f7d6c';
const ID2 = '9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d';
const AT = '2026-10-01T18:00:00.000Z';
const stamps = { createdAt: AT, updatedAt: AT };

export interface DtoFixture {
  name: string;
  schema: z.ZodObject;
  fixture: Record<string, unknown>;
  /** Un campo de dinero para probar que rechaza decimales (si el DTO tiene dinero). */
  moneyField?: string;
}

export const DTO_FIXTURES: DtoFixture[] = [
  {
    name: 'BranchDto',
    schema: dto.BranchDto,
    fixture: {
      id: ID,
      code: 'S1',
      name: 'Sucursal 1',
      legalName: 'Calzado SA de CV',
      taxId: 'CAL010101AB1',
      address: 'Centro',
      phone: '5512345678',
      email: 'tienda@ejemplo.com',
      imageUrl: '/uploads/branch/a.webp',
      logoUrl: '/uploads/branch/b.webp',
      ticketHeader: 'Gracias por su compra',
      ticketFooterMessage: 'Vuelva pronto',
      promoQrText: 'DESC10',
      promoQrCaption: 'Muestra este QR',
      timezone: 'America/Mexico_City',
      currency: 'MXN',
      taxRateBp: 1600,
      pricesIncludeTax: true,
      lowStockThreshold: 2,
      isActive: true,
      ...stamps,
    },
  },
  {
    name: 'CashRegisterDto',
    schema: dto.CashRegisterDto,
    fixture: { id: ID, branchId: ID2, code: 'C1', name: 'Caja 1', isActive: true, ...stamps },
  },
  {
    name: 'CashSessionDto',
    schema: dto.CashSessionDto,
    moneyField: 'openingAmount',
    fixture: {
      id: ID,
      cashRegisterId: ID2,
      openedById: ID2,
      openedAt: AT,
      openingAmount: 50000,
      closedById: ID2,
      closedAt: AT,
      expectedAmount: 100000,
      countedAmount: 98000,
      difference: -2000,
      status: 'CLOSED',
      ...stamps,
    },
  },
  {
    name: 'UserDto',
    schema: dto.UserDto,
    fixture: {
      id: ID,
      username: 'ana',
      fullName: 'Ana López',
      email: 'ana@ejemplo.com',
      phone: '5512345678',
      roleId: ID2,
      type: 'STAFF',
      isActive: true,
      mustChangePassword: false,
      lastLoginAt: AT,
      ...stamps,
    },
  },
  {
    name: 'RoleDto',
    schema: dto.RoleDto,
    fixture: { id: ID, code: 'SELLER', name: 'Vendedor', isSystem: true, ...stamps },
  },
  {
    name: 'PermissionDto',
    schema: dto.PermissionDto,
    fixture: { id: ID, code: 'pos.sell', module: 'pos', description: 'Vender', ...stamps },
  },
  {
    name: 'CategoryDto',
    schema: dto.CategoryDto,
    fixture: { id: ID, name: 'Calzado', parentId: ID2, isActive: true, ...stamps },
  },
  {
    name: 'BrandDto',
    schema: dto.BrandDto,
    fixture: { id: ID, name: 'Demo Calzado', isActive: true, ...stamps },
  },
  {
    name: 'ProductDto',
    schema: dto.ProductDto,
    moneyField: 'price',
    fixture: {
      id: ID,
      sku: 'ZAP0101',
      name: 'Zapato de piel dama',
      description: 'Piel',
      categoryId: ID2,
      brandId: ID2,
      type: 'VARIABLE',
      price: 89900,
      cost: 45000,
      tags: ['piel'],
      isActive: true,
      ...stamps,
    },
  },
  {
    name: 'ProductVariantDto',
    schema: dto.ProductVariantDto,
    moneyField: 'priceOverride',
    fixture: {
      id: ID,
      productId: ID2,
      sku: 'ZAP0101-25-NEG',
      barcode: '7501234567890',
      size: '25',
      color: 'Negro',
      material: 'Piel',
      priceOverride: 99900,
      isActive: true,
      ...stamps,
    },
  },
  {
    name: 'ProductImageDto',
    schema: dto.ProductImageDto,
    fixture: {
      id: ID,
      productId: ID2,
      variantId: ID2,
      url: '/uploads/product/a.webp',
      thumbUrl: '/uploads/product/a.thumb.webp',
      sortOrder: 0,
      ...stamps,
    },
  },
  {
    name: 'WarehouseDto',
    schema: dto.WarehouseDto,
    fixture: {
      id: ID,
      branchId: ID2,
      code: 'ALM1',
      name: 'Almacén principal',
      isActive: true,
      ...stamps,
    },
  },
  {
    name: 'ZoneDto',
    schema: dto.ZoneDto,
    fixture: {
      id: ID,
      warehouseId: ID2,
      code: 'A',
      name: 'Zona A',
      color: '#2563EB',
      isStaging: false,
      priority: 1,
      sortOrder: 1,
      isActive: true,
      ...stamps,
    },
  },
  {
    name: 'ContainerDto',
    schema: dto.ContainerDto,
    fixture: { id: ID, zoneId: ID2, code: '01', name: 'Anaquel 1', isActive: true, ...stamps },
  },
  {
    name: 'RackDto',
    schema: dto.RackDto,
    fixture: {
      id: ID,
      containerId: ID2,
      warehouseId: ID2,
      code: '03',
      locationCode: 'A-01-03',
      capacityUnits: 40,
      labelColor: '#16A34A',
      isActive: true,
      ...stamps,
    },
  },
  {
    name: 'StockLocationDto',
    schema: dto.StockLocationDto,
    fixture: { id: ID, variantId: ID2, rackId: ID2, quantity: 5, reservedQty: 1, ...stamps },
  },
  {
    name: 'InventoryMovementDto',
    schema: dto.InventoryMovementDto,
    fixture: {
      id: ID,
      variantId: ID2,
      fromRackId: ID2,
      toRackId: ID,
      quantity: 2,
      type: 'RELOCATE',
      userId: ID2,
      referenceType: 'CART',
      referenceId: ID2,
      note: 'Reacomodo',
      adjustmentReason: 'FOUND',
      capacityOverridden: false,
      createdAt: AT,
    },
  },
  {
    name: 'CartDto',
    schema: dto.CartDto,
    moneyField: 'discount',
    fixture: {
      id: ID,
      branchId: ID2,
      userId: ID2,
      number: 12,
      status: 'ACTIVE',
      label: 'Señora vestido rojo',
      customerName: 'María',
      discount: 0,
      ...stamps,
    },
  },
  {
    name: 'CartItemDto',
    schema: dto.CartItemDto,
    moneyField: 'unitPrice',
    fixture: {
      id: ID,
      cartId: ID2,
      variantId: ID2,
      sourceRackId: ID2,
      quantity: 1,
      unitPrice: 89900,
      discount: 0,
      ...stamps,
    },
  },
  {
    name: 'SaleDto',
    schema: dto.SaleDto,
    moneyField: 'total',
    fixture: {
      id: ID,
      folio: 'S1-000001',
      branchId: ID2,
      cashRegisterId: ID2,
      cashSessionId: ID2,
      sellerId: ID2,
      cashierId: ID2,
      cartId: ID2,
      customerName: 'María',
      subtotal: 124800,
      globalDiscount: 0,
      discountTotal: 0,
      taxRateBp: 1600,
      pricesIncludeTax: true,
      taxTotal: 17214,
      total: 124800,
      status: 'CANCELLED',
      cancelledAt: AT,
      cancelledById: ID2,
      cancelReason: 'Error de captura',
      ...stamps,
    },
  },
  {
    name: 'SaleItemDto',
    schema: dto.SaleItemDto,
    moneyField: 'lineTotal',
    fixture: {
      id: ID,
      saleId: ID2,
      variantId: ID2,
      sourceRackId: ID2,
      skuSnapshot: 'ZAP0101-25-NEG',
      nameSnapshot: 'Zapato de piel dama',
      variantLabelSnapshot: '25 · Negro',
      unitPrice: 89900,
      quantity: 1,
      discount: 0,
      lineTotal: 89900,
      createdAt: AT,
    },
  },
  {
    name: 'PaymentDto',
    schema: dto.PaymentDto,
    moneyField: 'amount',
    fixture: {
      id: ID,
      saleId: ID2,
      method: 'CASH',
      amount: 124800,
      received: 130000,
      change: 5200,
      reference: null,
      createdAt: AT,
    },
  },
];
